---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-cephfs-pvc
  namespace: busybox-sample
  labels:
    appname: busybox
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ocs-external-storagecluster-cephfs
  resources:
    requests:
      storage: 10Gi
