apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: amq-dr
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: amq-dr-placement
        requeueAfterSeconds: 180
  template:
    metadata:
      name: amq-dr-{{name}}
      labels:
        velero.io/exclude-from-backup: "true"
    spec:
      destination:
        namespace: amq-dr
        server: "{{server}}"
      project: default
      source:
        path: rdr
        repoURL: https://github.com/prsurve/strimzi-kafka-operator
        targetRevision: rdr
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: amq-dr-placement
  namespace: openshift-gitops
spec:
  predicates:
    - requiredClusterSelector:
        claimSelector: {}
        labelSelector:
          matchExpressions:
            - key: name
              operator: In
              values:
                - PLACEHOLDER
