apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    appname: busybox
  name: busybox-pvc-68
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 61Gi
  storageClassName: ocs-external-storagecluster-ceph-rbd
