apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    appname: busybox-7
  name: busybox-7
spec:
  selector:
    matchLabels:
      workload: busybox-7
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        workload: busybox-7
    spec:
      containers:
      - command: ["/bin/sh", "-c"]
        args:
          - wget  https://raw.githubusercontent.com/red-hat-storage/ocs-workloads/io-pattern-busybox/rdr/busybox/scripts/simple_io.sh -O /mnt/test/simple_io.sh;
            chmod +x /mnt/test/simple_io.sh;
            /mnt/test/simple_io.sh
        image: quay.io/vcppds7878/busybox:latest
        imagePullPolicy: IfNotPresent
        name: busybox
        volumeMounts:
        - mountPath: /mnt/test
          name: mypvc
      volumes:
      - name: mypvc
        persistentVolumeClaim:
          claimName: busybox-pvc-7
          readOnly: false
