---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fluentd-pvc
  namespace: fluentd
  labels:
    appname: fluentd-daemon
spec:
  accessModes:
  - ReadWriteMany
  volumeMode: Block
  storageClassName: ocs-external-storagecluster-ceph-rbd
  resources:
    requests:
      storage: 50Gi
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-daemon
  namespace: fluentd
  labels:
    k8s-app: fluentd-daemon
spec:
  selector:
    matchLabels:
      name: fluentd-daemon
  template:
    metadata:
      labels:
        name: fluentd-daemon
    spec:
      containers:
      - name: fluentd-daemon
        image: quay.io/fluentd_elasticsearch/fluentd:v2.5.2
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
            #volumeMounts:
            #- name: volume
         #mountPath: /var/log
        volumeDevices:
        - devicePath: /dev/rbdblock
          name: volume
      terminationGracePeriodSeconds: 30
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: fluentd-pvc

